language: python
python:
  - "2.7"
install:
  - "wget -O - http://apt.mopidy.com/mopidy.gpg | sudo apt-key add -"
  - "sudo wget -O /etc/apt/sources.list.d/mopidy.list http://apt.mopidy.com/mopidy.list"
  - "sudo apt-get update"
  - "sudo apt-get install python-all-dev libffi-dev libspotify-dev pandoc"
  - "pandoc -f markdown -t rst -o README.rst README.md"
  - "pip install -r requirements.txt"
  - "pip install ."
script: ./manage.py test
deploy:
  provider: pypi
  user: jbraegger
  password:
    secure: P3dSxH4hgJ6JdnGc4zcCneM/jn2qczOh11uxFSJGHEvkMvL4vOrZ0yOiE8BBInUBeT/4kVfWNuBghibS1P06AlWWvUz66KHc719mpHBA3On+q/0troVXT1Pl9xiEr8ITvQda7wWgSZaxSVpaZnkMJZQQkR3ucc7p6qm4mygPyjs=
  on:
    all_branches: true
    repo: rckclmbr/pyportify
    tags: true
